# Schema for the configuration files of the Smart Date Recur module.
field.formatter.settings.smartdate_recurring:
  type: field.formatter.settings.datetime_default
  label: 'Smart date default display format settings'
  mapping:
    timezone_override:
      type: string
      label: 'Time zone override'
      translation context: 'Smart date display'
    format:
      type: string
      label: 'Format'
      translation context: 'Smart date display'
    force_chronological:
      type: boolean
      label: 'Force chronological'
      translation context: 'Smart date display'
    past_display:
      type: int
      label: 'Recent Instances'
      translation context: 'Smart date display'
    upcoming_display:
      type: int
      label: 'Upcoming Instances'
      translation context: 'Smart date display'
    show_next:
      type: boolean
      label: 'Show next instance separately'
      translation context: 'Smart date display'
